name: Deploy to GitHub Pages

on:
  push:
    branches: ['new-workflow']

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: actions/setup-node@v4
        with:
          node-version: 16 # Bun requires Node.js v16 or later to install

      - name: Install Bun and dependencies
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc
          bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          bun build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
